image: yuih/frontistr_libs:latest

stages:
    - build
    - test
    - deploy

make:
    stage: build
    script:
        - mkdir -p build
        - cd build
        - cmake .. -DWITH_DOCS=ON
        - make -j $(nproc)
    artifacts:
        paths:
            - build/
        expire_in: 100min

test_static:
    stage: test
    dependencies:
        - make
    before_script:
        - apt install -y ruby
    script:
        - cd build
        - ctest -L static --output-on-failure

test_fragile:
    stage: test
    dependencies:
        - make
    before_script:
        - apt install -y ruby
    script:
        - cd build
        - ctest -L "(eigen|heat|dynamic)" --output-on-failure

pages:
    stage: deploy
    script:
        - apt install -y doxygen python wget git graphviz
        - mkdir -p public
        - cd build/doc/; doxygen ./Doxyfile; cd -
        - wget https://bootstrap.pypa.io/get-pip.py; python get-pip.py
        - pip install mkdocs
        - pip install mkdocs-bootstrap
        - pip install mkdocs-windmill
        - pip install python-markdown-math
        - git submodule update -i
        - cd doc; ./create_docs.sh; cd ..
        - cp -r doc/manuals/* public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - ci-master



############################################################
#     build_serial:
#         stage: build
#         only:
#             - tokunaga/ci-test
#         script:
#             - mkdir -p build
#             - cd build
#             - rm -rf ./*
#             - cmake -DWITH_TOOLS=OFF -DWITH_MPI=OFF -DWITH_METIS=OFF -DWITH_MUMPS=OFF ..
#             - make
#             - cd ../
#         artifacts:
#             paths:
#                 - build/fistr1/fistr1
#             expire_in: 1 month
#
#             build_parallel:
#                 stage: build
#                 only:
#                     - tokunaga/ci-test
#                 script:
#                     - mkdir -p build_p
#                     - cd build_p
#                     - rm -rf ./*
#                     - cmake -DWITH_TOOLS=ON -DWITH_MPI=ON -DWITH_METIS=ON -DWITH_MUMPS=ON ..
#                     - make
#                     - cd ../
#                 artifacts:
#                     paths:
#                         - build_p/fistr1/fistr1
#                         - build_p/fistr1/tools/neu2fstr
#                         - build_p/hecmw1/tools/hec2rcap
#                         - build_p/hecmw1/tools/hecmw_part1
#                         - build_p/hecmw1/tools/hecmw_vis1
#                         - build_p/hecmw1/tools/rconv
#                         - build_p/hecmw1/tools/rmerge
#                     expire_in: 1 month
#
#                     test_serial:
#                         stage: test
#                         only:
#                             - tokunaga/ci-test
#                         script:
#                             - apt -y install ssh
#                             - apt -y install ruby
#                             - cd build
#                             - make test CTEST_OUTPUT_ON_FAILURE=1
#                         artifacts:
#                             paths:
#                                 - build/Testing/Temporary/LastTest.log
#                                 - build/Testing/Temporary/LastTestsFailed.log
#                             expire_in: 1 month
#                             when: on_failure
#
#                             test_parallel:
#                                 stage: test
#                                 only:
#                                     - tokunaga/ci-test
#                                 script:
#                                     - apt -y install ssh
#                                     - apt -y install ruby
#                                     - cd build_p
#                                     - make test CTEST_OUTPUT_ON_FAILURE=1
#                                 artifacts:
#                                     paths:
#                                         - build_p/Testing/Temporary/LastTest.log
#                                         - build_p/Testing/Temporary/LastTestsFailed.log
#                                     expire_in: 1 month
#                                     when: on_failure
