image: registry.ritc.jp/ricos/frontistr/build:latest

variables:
  AWS_DEFAULT_REGION: ap-northeast-1
  BUCKET_NAME: ricos-frontistr-manual-preview

stages:
    - build
    - test
    - deploy

make:
    stage: build
    script:
        - cmake -Bbuild -H.
        - cmake --build build
    artifacts:
        paths:
            - build/
        expire_in: 100min

test_static:
    stage: test
    dependencies:
        - make
    script:
        - cd build
        - ctest -L static --output-on-failure

test_fragile:
    stage: test
    dependencies:
        - make
    allow_failure: true
    script:
        - cd build
        - ctest -L "(eigen|heat|dynamic)" --output-on-failure

document:
    image: registry.ritc.jp/ricos/frontistr/document:latest
    stage: build
    before_script:
        - pip3 install -r doc/requirements.txt
    script:
        - ./doc/create_docs.sh
        - rm -rf public
        - mv doc/manuals public
    artifacts:
        paths:
            - public
        expire_in: 100min
    variables:
        GIT_SUBMODULE_STRATEGY: recursive

doxygen:
    image: registry.ritc.jp/ricos/frontistr/document:latest
    stage: build
    script:
        - cmake -Bbuild_doc -H. -DWITH_DOC=ON
        - make -C build_doc doc
        - rm -rf public
        - mkdir -p public
        - mv build_doc/doc/html public/doxygen
    artifacts:
        paths:
            - public
        expire_in: 100min

pages:
    stage: deploy
    dependencies:
        - document
        - doxygen
    script:
        - ls public
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - ci-master

deploy-s3:
  image: python
  stage: deploy
  dependencies:
    - doxygen
    - document
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive --acl public-read
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}
    on_stop: clean-s3

clean-s3:
  image: python
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual

############################################################
#     build_serial:
#         stage: build
#         only:
#             - tokunaga/ci-test
#         script:
#             - mkdir -p build
#             - cd build
#             - rm -rf ./*
#             - cmake -DWITH_TOOLS=OFF -DWITH_MPI=OFF -DWITH_METIS=OFF -DWITH_MUMPS=OFF ..
#             - make
#             - cd ../
#         artifacts:
#             paths:
#                 - build/fistr1/fistr1
#             expire_in: 1 month
#
#             build_parallel:
#                 stage: build
#                 only:
#                     - tokunaga/ci-test
#                 script:
#                     - mkdir -p build_p
#                     - cd build_p
#                     - rm -rf ./*
#                     - cmake -DWITH_TOOLS=ON -DWITH_MPI=ON -DWITH_METIS=ON -DWITH_MUMPS=ON ..
#                     - make
#                     - cd ../
#                 artifacts:
#                     paths:
#                         - build_p/fistr1/fistr1
#                         - build_p/fistr1/tools/neu2fstr
#                         - build_p/hecmw1/tools/hec2rcap
#                         - build_p/hecmw1/tools/hecmw_part1
#                         - build_p/hecmw1/tools/hecmw_vis1
#                         - build_p/hecmw1/tools/rconv
#                         - build_p/hecmw1/tools/rmerge
#                     expire_in: 1 month
#
#                     test_serial:
#                         stage: test
#                         only:
#                             - tokunaga/ci-test
#                         script:
#                             - apt -y install ssh
#                             - apt -y install ruby
#                             - cd build
#                             - make test CTEST_OUTPUT_ON_FAILURE=1
#                         artifacts:
#                             paths:
#                                 - build/Testing/Temporary/LastTest.log
#                                 - build/Testing/Temporary/LastTestsFailed.log
#                             expire_in: 1 month
#                             when: on_failure
#
#                             test_parallel:
#                                 stage: test
#                                 only:
#                                     - tokunaga/ci-test
#                                 script:
#                                     - apt -y install ssh
#                                     - apt -y install ruby
#                                     - cd build_p
#                                     - make test CTEST_OUTPUT_ON_FAILURE=1
#                                 artifacts:
#                                     paths:
#                                         - build_p/Testing/Temporary/LastTest.log
#                                         - build_p/Testing/Temporary/LastTestsFailed.log
#                                     expire_in: 1 month
#                                     when: on_failure
